### ISSUE TITLE
Error with nullish coalescing operator and optional chaining in realtime client

### ISSUE THREAD

**Issue by griffinatkyron** [speechmatics/speechmatics-js-sdk#16]
**Describe the bug**
During asset precompilation / webpack, we got the following error after adding the speechmatics module to our application:

Step #0 - "build image": ERROR in ./node_modules/speechmatics/dist/realtime/client.js 114:86
Step #0 - "build image": Module parse failed: Unexpected token (114:86)
Step #0 - "build image": File was processed with these loaders:
Step #0 - "build image":  * ./node_modules/babel-loader/lib/index.js
Step #0 - "build image": You may need an additional loader to handle the result of these loaders.
Step #0 - "build image": |     const runtimeKey = typeof this.connectionConfig.apiKey === "string" ? this.connectionConfig.apiKey : await this.connectionConfig.apiKey();
Step #0 - "build image": |     let error = null;
Step #0 - "build image": >     await this.rtSocketHandler.connect(`${this.connectionConfig.realtimeUrl}/${config?.transcription_config?.language || import_handlers.defaultLanguage}`, runtimeKey, this.connectionConfig.appId).catch(err => {
Step #0 - "build image": |       error = new Error(`Unable to connect to RT runtime: ${JSON.stringify(err)}`);
Step #0 - "build image": |     });
Step #0 - "build image":  @ ./node_modules/speechmatics/dist/client.js 35:20-48
Step #0 - "build image":  @ ./node_modules/speechmatics/dist/index.js
Step #0 - "build image":  @ ./app/javascript/controllers/realtimeTranscriptionController.ts
Step #0 - "build image":  @ ./app/javascript/components/player/LessonOpenEnded.jsx
Step #0 - "build image":  @ ./app/javascript/components/player/QuestionInputs.jsx
Step #0 - "build image":  @ ./app/javascript/components sync ^\.\/.*$
Step #0 - "build image":  @ ./app/javascript/packs/application.js
Step #0 - "build image": 
Step #0 - "build image": ERROR in ./node_modules/speechmatics/dist/batch/client.js 55:25
Step #0 - "build image": Module parse failed: Unexpected token (55:25)
Step #0 - "build image": File was processed with these loaders:
Step #0 - "build image":  * ./node_modules/babel-loader/lib/index.js
Step #0 - "build image": You may need an additional loader to handle the result of these loaders.
Step #0 - "build image": |   }
Step #0 - "build image": |   get apiKey() {
Step #0 - "build image": >     return this._apiKey ?? (typeof this.config.apiKey === "string" ? this.config.apiKey : void 0);
Step #0 - "build image": |   }
Step #0 - "build image": |   async refreshApiKey() {
Step #0 - "build image":  @ ./node_modules/speechmatics/dist/batch/index.js 22:26-45
Step #0 - "build image":  @ ./node_modules/speechmatics/dist/index.js
Step #0 - "build image":  @ ./app/javascript/controllers/realtimeTranscriptionController.ts
Step #0 - "build image":  @ ./app/javascript/components/player/LessonOpenEnded.jsx
Step #0 - "build image":  @ ./app/javascript/components/player/QuestionInputs.jsx
Step #0 - "build image":  @ ./app/javascript/components sync ^\.\/.*$
Step #0 - "build image":  @ ./app/javascript/packs/application.js

This is because speechmatics' usages of the nullish coalescing operator and the optional chaining operator were not transpiled. 

The fix on our side was to add two babel packages: 
@babel/plugin-proposal-optional-chaining
@babel/plugin-transform-nullish-coalescing-operator

I wanted to raise the issue, because others would probably experience the same. Thanks.

**Comment by TudorCRL** [comment]
Thanks @griffinatkyron for raising the issue, and thanks for sharing the fix. We'll see if we can push a fix for it on our end so the fix you detail isn't needed

**Comment by nickgerig** [comment]
@griffinatkyron What version of Babel are you using? We are not sure there is anything for us to do here as this plugin should be included as of 2020.
