### ISSUE TITLE
Documentation on Realtime streaming misses Audio filtering and Audio events

### ISSUE THREAD

**Issue by willemmulder** [speechmatics/speechmatics-js-sdk#55]
**Describe the bug**
Did not know where to post this, but the Realtime API ref at https://docs.speechmatics.com/rt-api-ref does not contain the config options for Audio filtering and Audio events. Could this be added?

**Comment by willemmulder** [comment]
Great, thanks!

**Comment by willemmulder** [comment]
Any update on this? Or maybe I'm looking in the wrong place?

**Comment by TudorCRL** [comment]
Hi @willemmulder, sorry for not getting back to you sooner - I think these features should be added now, you can find them at these urls: [audio filtering](https://docs.speechmatics.com/features/audio-filtering) and [audio events](https://docs.speechmatics.com/features/audio-events). I've just made sure that that audio filtering and events are also listed in the [rt spec](https://docs.speechmatics.com/rt-api-ref#startrecognition) in the rt api reference

**Comment by willemmulder** [comment]
Thanks @TudorCRL! Consider this closed.

**Comment by willemmulder** [comment]
Sorry, had to reopen this. The `AudioEventStarted ` and `AudioEventEnded ` events are not listed on https://docs.speechmatics.com/rt-api-ref

**Comment by TudorCRL** [comment]
@willemmulder ah yes! Sorry about that, completely missed it. I'll get those added soon and let you know when they're ready

**Comment by willemmulder** [comment]
Thanks! :-)

**Comment by TudorCRL** [comment]
@willemmulder I've added those events to the ref now, you can find them [here](https://docs.speechmatics.com/rt-api-ref#audioeventstarted)

**Comment by willemmulder** [comment]
Thanks; closed! For real now! ;-)
