### ISSUE TITLE
Timeout as parameter

### ISSUE THREAD

**Issue by erkkimon** [speechmatics/speechmatics-js-sdk#61]
**Is your feature request related to a problem? Please describe.**
15 minutes timeout is problematic because over 1 hour recordings can take more than 15 minutes to transcribe. Now the 15 minutes timeout is hardcoded.

**Describe the solution you'd like**
It should be possible to define longer timeout, because the appropriate timeout depends on the use-case.

**Describe alternatives you've considered**
I have considered overriding the method but decided to fork the repository.

**Additional context**
I'm talking about [this](https://github.com/inderes/speechmatics-js-sdk-timeout-fix/blob/600f114eb648302ce21120beb14bfacdce36c22a/src/batch/client.ts#L138) line.

**Comment by erkkimon** [comment]
Could this small improvement be added to the repo soonish? Hardcoded 15 minutes timeout is quite a big limitation but simple to fix, so it has a good ROI. :)

**Comment by mnemitz** [comment]
A configurable timeout to the transcribe function has now been added to the new package:
 https://www.npmjs.com/package/@speechmatics/batch-client

If you encounter any issues let me know.

**Comment by erkkimon** [comment]
@mnemitz Wonderful, thanks!
