### ISSUE TITLE
Job rejected due to invalid audio - using Speechmatics API in Node.js

### ISSUE THREAD

**Issue by Yasin-97** [speechmatics/speechmatics-js-sdk#89]
I'm trying to transcribe `wav` files using the free version of Speechmatics API in a Node.js application but encounter this error : `{ code: 400, error: 'Job rejected due to invalid audio' }`.

**Setup:**

- Node.js version: 20.18.0
- Speechmatics Batch Client: @speechmatics/batch-client
- API key: Free version
- Audio file format: WAV

**Code:**
```dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const upload = multer({ dest: 'uploads/' });

const apiKey = process.env.API_KEY;
const client = new BatchClient({ apiKey, appId: 'nodeJS-example' });

app.post('/transcribe', upload.single('audio'), async (req, res) => {
  const audioFile = req.file.path;

  try {
    const blob = await fs.readFile(audioFile);
    const file = new File([blob], req.file.originalname);

    const response = await client.transcribe(
      file,
      { transcription_config: { language: 'en' } },
      'json-v2'
    );

    const transcript = typeof response === 'string'
      ? response
      : response.results.map(r => r.alternatives?.[0].content).join(' ');

    res.json({ transcript });
  } catch (error) {
    res.status(500).json({ error: error.message });
  } finally {
    await fs.unlink(audioFile);
  }
});
 ```
 
 **Error Message:**
 
 ```
{
  "code": 400,
  "error": "Job rejected due to invalid audio"
}
 ```

**Comment by mnemitz** [comment]
Hi, thanks for getting in touch.

I haven't run this code, but I think you may want

```js
 const blob = await fs.openAsBlob(audioFile);
 ```
 
 instead of
 
 ```js
const blob = await fs.readFile(audioFile);
 ```
 
 `fs.readFile` doesn't return a promise, it returns `undefined` and expects a callback: https://nodejs.org/api/fs.html#fsreadfilepath-options-callback.
 
 See our [NodeJS example here])https://github.com/speechmatics/speechmatics-js-sdk/blob/main/examples/nodejs/batch-example.ts#L26).
